### PR TITLE
Fix pressComposer under IOS 9.3

### PR DESCRIPTION
**Pull request by thibaultzanini**

### CODE REVIEW

**Comment by hthetiot** [comment]
Can it be done using feature detection instead ?

**Comment by hthetiot** [comment]
lgtm

**Comment by hthetiot** [comment]
@thibaultzanini check test if you can then merge

**Comment by thibaultzanini** [comment]
@benoitmarchant What was the issue already under IOS 9.3 and the press-composer? I can't reproduce it on master. This PR might be outdated.

**Comment by marchant** [comment]
couldn't reproduce anymore, iOS 9.3 getting old as well, closing

**Pull request closed without merging**
