### PR TITLE
Eliminate creation of a new Promise in Component

### PR DESCRIPTION
**Pull request by rayshan**
Had this one sitting in my stash.

### CODE REVIEW

**Comment by thibaultzanini** [comment]
LGTM

**Comment by francoisfrisch** [comment]
This change is not equivalent, it means that the promise will not reject if
instantiateTemplate fails for some reason. You should throw in the catch.

**Comment by thibaultzanini** [comment]
Thanks for the feedback @francoisfrisch. :)

I think I'm going to remove the catch statement anyway.

It's kind of redundant, because errors are already "tracked" within the `_instantiateTemplate` function:
- https://github.com/montagejs/montage/blob/master/ui/component.js#L1465
- https://github.com/montagejs/montage/blob/master/ui/component.js#L1486 

Plus, calling the error function of the console object in the catch gives you the following error: `TypeError: Illegal Invocation`.

**Comment by rayshan** [comment]
Thanks guys.

**Pull request merged**
