### PR TITLE
Support mopped mjson file and wait for modules to be ready.

### PR DESCRIPTION
**Pull request by thibaultzanini**

### CODE REVIEW

**Comment by tejaede** [comment]
@hthetiot @thibaultzanini I tried with a couple different combinations of mop & mr and hit the following error on all .mjson files. 

screen shot 2018-01-10 at 7 20 27 pm

I will try again later today and document the mop & mr versions along with the results.

**Comment by tejaede** [comment]
Successful for unmopped applications with mr#master.

Successful for mopped applications with https://github.com/montagejs/mr/pull/129

**Comment by hthetiot** [comment]
merged https://github.com/montagejs/mr/pull/129 will release and then enforce version in this PR

**Comment by hthetiot** [comment]
Let wait for build, then i will merge

**Comment by hthetiot** [comment]
k green lights

**Pull request merged**
