### PR TITLE
Tentative tweak to make improvements to the use of requestAnimation…

### PR DESCRIPTION
**Pull request by marchant**
…Frame

- removes use of workaround for lack of native requestAnimationFrame which exists in IE10

### CODE REVIEW

**Comment by hthetiot** [comment]
Why removing the feature detection in place ? Fallback should still be available.

**Comment by hthetiot** [comment]
The only issue I have is with removing the shim and not supporting prefixed webkit.
- http://caniuse.com/#feat=requestanimationframe

Cc @BnTejaede can you confirm PDC app is ok without this shim on iOS notably.

**Comment by BnTejaede** [comment]
@hthetiot @marchant I cannot load Contour in mobile Safari with the PR, but I can with Montage#master. I do not have the bandwidth to investigate further at the moment, but it appears that Harold may be right about the webkit prefixes.

**Comment by hthetiot** [comment]
@marchant need someking of rebase on master, I dont know why this push is weird.

**Comment by hthetiot** [comment]
need re-push cause PR is a mess.
Also see fix for regression #1923
Sorry.

**Pull request closed without merging**
