### PR TITLE
Bugs/data service deserialization

### PR DESCRIPTION
**Pull request by tejaede**

### CODE REVIEW

**Comment by johnnykahalawai** [comment]
@tejaede -

Is deserializeSelf async in any other object?  Maybe I'm wrong but it seems like we are hijacking a function to do something we want which is non-standard.

cc: @benoitmarchant

**Comment by marchant** [comment]
montage reviver already expects deserializeSelf to eventually return a thenable object, to deal with objects that can only deserialize themselves asynchronously, I don't think this is hijacking

**Comment by johnnykahalawai** [comment]
OK then!

**Comment by tejaede** [comment]
@johnnykahalawai 

Snippet that Benoit is referring to, if you're curious:
https://github.com/montagejs/montage/blob/master/core/serialization/deserializer/montage-reviver.js#L646-L659


Once I resolve the Travis build I will merge.

**Pull request merged**
