### PR TITLE
Fixes a resizing bug in Flow

### PR DESCRIPTION
**Pull request by marchant**
… a precision logic error

### CODE REVIEW

**Comment by marchant** [comment]
Doing more tests in different flows

**Comment by hthetiot** [comment]
- https://travis-ci.org/montagejs/montage/jobs/259957752#L2686

**Comment by thibaultzanini** [comment]
@benoitmarchant could you update this PR please the tests fail.

**Comment by thibaultzanini** [comment]
https://github.com/montagejs/montage/pull/1849

**Pull request closed without merging**
