### PR TITLE
Fix for a bug that prevented a repetition clear selection to work.

### PR DESCRIPTION
**Pull request by marchant**

### CODE REVIEW

**Comment by thibaultzanini** [comment]
@marchant It looks like to fix some specs but brings some new.
https://github.com/montagejs/montage/blob/master/test/run.js#L46

**Comment by rayshan** [comment]
Random question for style guide - why `EMPTY_ARRAY`, not `emptyArray`?

**Comment by thibaultzanini** [comment]
I assume it's because we want to distinguish constant variables. @marchant Can you confirm it?

**Comment by rayshan** [comment]
I think you're right, @marchant mentioned it in passing. Thanks @thibaultzanini

**Comment by marchant** [comment]
All range-controller tests now pass, merging

**Pull request merged**
